.\" $Id: tdindent.1,v 1.3 2010/10/28 10:46:08 tom Exp $
.\" Copyright:  2010 by Thomas E. Dickey
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the
.\" "Software"), to deal in the Software without restriction, including
.\" without limitation the rights to use, copy, modify, merge, publish,
.\" distribute, distribute with modifications, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included
.\" in all copies or portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
.\" OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
.\" DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
.\" OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
.\" THE USE OR OTHER DEALINGS IN THE SOFTWARE.
.\"
.\" Except as contained in this notice, the name(s) of the above copyright
.\" holders shall not be used in advertising or otherwise to promote the
.\" sale, use or other dealings in this Software without prior written
.\" authorization.
.TH TDINDENT 1
.ds n cindent
.SH NAME
tdindent \- utility scripts for \fI\*n\fP.
.SH SYNOPSIS
.B tdindent [\fIoptions\fP]
.SH DESCRIPTION
This is a wrapper for the \fI\*n\fP program, which adds options.
Unrecognized options are passed to \fI\*n\fP.
.PP
Options:
.TP 5
\-h
display a usage message for \fItdindent\fP.
.TP 5
\-n
perform indent and show difference without saving the result.
This is useful for previewing \fI\*n\fP's splitting of lines.
.TP 5
\-\-profile file
get settings, use those to override \fB.indent.pro\fP.
The script looks in the current directory,
the user's home directory,
or in a configuration-specific location.
.TP 5
\-s
convert tabs to spaces in the updated file.
The script relies on the settings from the \fB\-\-profile\fP option
to get the tab-size for expansion.
.SH OTHER SCRIPTS
There are several profiles and corresponding wrapper scripts:
.TP 5
bsd-indent
This uses the "original" (Sun) indent settings.
.TP 5
cdk-indent
These are the settings used for the \fICDK\fP (curses development kit).
.TP 5
flx-indent
These are the settings used for \fIreflex\fP's skeleton.
.TP 5
gnu-indent
This uses the GNU indent settings.
.TP 5
jpf-indent
These are the indent settings used by Juergen Pfeifer for ncurses.
.TP 5
lnx-indent
These are the settings used for the \fIlynx\fP web browser.
.TP 5
ncu-indent
These are the indent settings used for \fIncurses\fP, as well as
other programs such as \fIxterm\fP, \fIvile\fP, \fIdiffstat\fP.
.TP 5
tin-indent
These are the settings used for the \fItin\fP newsreader.
.TP 5
vtt-indent
These are the settings used for \fIvttest\fP.
.TP 5
yak-indent
These are the settings used for \fIbyacc\fP (Berkeley Yacc).
.SH ENVIRONMENT
.TP 5
INDENT_PROG
Set the name of the \fIindent\fP program.
The default value is configuration-specific,
but uses an environment variable to allow temporary customization.
.TP 5
INDENT_DATA
Set the location where profile files are found.
This is configuration-specific.
.SH NOTES
The line numbering presented by GNU indent is generally incorrect.
Use \*n, at
.RS
http://invisible-island.net/gnu-patches/
.RE
.PP
While GNU indent does not support the \fB\-\-profile\fP option,
\fItdlint\fP checks for this and will attempt to pass the profile's
contents on the command-line.
.SH SEE ALSO
\*n(1).
