#! /bin/sh
# prerm script for indent

set -e

ALT=cindent
PKG=indent

if [ $1 != "upgrade" ]; then
	update-alternatives --remove $PKG /usr/bin/$ALT
	update-alternatives --remove $PKG /usr/share/man/man1/$ALT.1.gz
fi

#DEBHELPER#

exit 0
