Read profile ./scripts/cdk-profile
case007-cdk.c:4:3: Warning: Line split #2 at NAMES
case007-cdk.c:11:30: Warning: Line split #2 at {
case007-cdk.c:48:55: Warning: Line split #2 at {
case007-cdk.c:49:50: Warning: Line split #2 at {
case007-cdk.c:55:25: Warning: Line split #2 at {
case007-cdk.c:58:36: Warning: Line split #2 at {
There were 39 output lines and 1 comments
(Lines with comments)/(Lines with code):  0.026
** updated case007-cdk.c
