Read profile ./scripts/jpf-profile
case002-jpf.c:10:67: Warning: Line split #2 at {
case002-jpf.c:12:7: Warning: Line split #2 at else
case002-jpf.c:12:59: Warning: Line split #2 at {
case002-jpf.c:14:7: Warning: Line split #2 at else
case002-jpf.c:14:81: Warning: Line split #2 at {
case002-jpf.c:16:7: Warning: Line split #2 at else
case002-jpf.c:16:12: Warning: Line split #2 at {
case002-jpf.c:30:41: Warning: Line split #2 at {
case002-jpf.c:32:7: Warning: Line split #2 at else
case002-jpf.c:32:48: Warning: Line split #2 at {
case002-jpf.c:44:23: Warning: Line split #2 at {
case002-jpf.c:46:41: Warning: Line split #2 at {
case002-jpf.c:48:11: Warning: Line split #2 at else
case002-jpf.c:48:43: Warning: Line split #2 at {
case002-jpf.c:50:11: Warning: Line split #2 at else
case002-jpf.c:50:49: Warning: Line split #2 at {
case002-jpf.c:52:11: Warning: Line split #2 at else
case002-jpf.c:52:16: Warning: Line split #2 at {
There were 72 output lines and 4 comments
(Lines with comments)/(Lines with code):  0.056
** updated case002-jpf.c
