case002-xorg.c:12: Warning:Line broken 2
case002-xorg.c:14: Warning:Line broken 2
case002-xorg.c:16: Warning:Line broken 2
case002-xorg.c:32: Warning:Line broken 2
case002-xorg.c:48: Warning:Line broken 2
case002-xorg.c:50: Warning:Line broken 2
case002-xorg.c:52: Warning:Line broken 2
There were 60 non-blank output lines and 4 comments
(Lines with comments)/(Lines with code):  0.068
** updated case002-xorg.c
