option: ly
Read profile ./scripts/cdk-profile
case003-cdk.l:7:28: Warning: Line split #2 at {
case003-cdk.l:9:3: Warning: Line split #2 at else
case003-cdk.l:9:36: Warning: Line split #2 at {
case003-cdk.l:12:3: Warning: Line split #2 at else
case003-cdk.l:12:8: Warning: Line split #2 at {
There were 60 output lines and 5 comments
(Lines with comments)/(Lines with code):  0.091
** updated case003-cdk.l
