Read profile ./scripts/jpf-profile
case002-jpf.c:10:67: Warning: Line split #2 at {
case002-jpf.c:12:7: Warning: Line split #2 at else
case002-jpf.c:12:59: Warning: Line split #2 at {
case002-jpf.c:14:7: Warning: Line split #2 at else
case002-jpf.c:14:81: Warning: Line split #2 at {
case002-jpf.c:16:7: Warning: Line split #2 at else
case002-jpf.c:16:12: Warning: Line split #2 at {
case002-jpf.c:30:41: Warning: Line split #2 at {
case002-jpf.c:32:7: Warning: Line split #2 at else
case002-jpf.c:32:48: Warning: Line split #2 at {
There were 41 output lines and 3 comments
(Lines with comments)/(Lines with code):  0.073
** updated case002-jpf.c
