Read profile ./scripts/xxx-profile
case007-xxx.c:4:3: Warning: Line split #2 at NAMES
case007-xxx.c:11:30: Warning: Line split #2 at {
case007-xxx.c:50:55: Warning: Line split #2 at {
case007-xxx.c:51:50: Warning: Line split #2 at {
case007-xxx.c:57:25: Warning: Line split #2 at {
case007-xxx.c:60:36: Warning: Line split #2 at {
There were 40 output lines and 1 comments
(Lines with comments)/(Lines with code):  0.026
** updated case007-xxx.c
