option: ly
Read profile ./scripts/gnu-profile
case003-gnu.l:7:28: Warning: Line split #2 at {
case003-gnu.l:9:3: Warning: Line split #2 at else
case003-gnu.l:9:36: Warning: Line split #2 at {
case003-gnu.l:12:3: Warning: Line split #2 at else
case003-gnu.l:12:8: Warning: Line split #2 at {
There were 64 output lines and 5 comments
(Lines with comments)/(Lines with code):  0.085
** updated case003-gnu.l
