Read profile ./scripts/yak-profile
case007-yak.c:4:3: Warning: Line split #2 at NAMES
case007-yak.c:11:30: Warning: Line split #2 at {
case007-yak.c:50:55: Warning: Line split #2 at {
case007-yak.c:51:50: Warning: Line split #2 at {
case007-yak.c:57:25: Warning: Line split #2 at {
case007-yak.c:60:36: Warning: Line split #2 at {
There were 40 output lines and 1 comments
(Lines with comments)/(Lines with code):  0.026
** updated case007-yak.c
