Read profile ./scripts/yak-profile
case002-yak.c:10:67: Warning: Line split #2 at {
case002-yak.c:12:7: Warning: Line split #2 at else
case002-yak.c:12:59: Warning: Line split #2 at {
case002-yak.c:14:7: Warning: Line split #2 at else
case002-yak.c:14:81: Warning: Line split #2 at {
case002-yak.c:16:7: Warning: Line split #2 at else
case002-yak.c:16:12: Warning: Line split #2 at {
There were 28 output lines and 3 comments
(Lines with comments)/(Lines with code):  0.107
** updated case002-yak.c
