Read profile ./scripts/cdk-profile
case002-cdk.c:10:67: Warning: Line split #2 at {
case002-cdk.c:12:7: Warning: Line split #2 at else
case002-cdk.c:12:59: Warning: Line split #2 at {
case002-cdk.c:14:7: Warning: Line split #2 at else
case002-cdk.c:14:81: Warning: Line split #2 at {
case002-cdk.c:16:7: Warning: Line split #2 at else
case002-cdk.c:16:12: Warning: Line split #2 at {
case002-cdk.c:30:41: Warning: Line split #2 at {
case002-cdk.c:32:7: Warning: Line split #2 at else
case002-cdk.c:32:48: Warning: Line split #2 at {
There were 40 output lines and 3 comments
(Lines with comments)/(Lines with code):  0.075
** updated case002-cdk.c
