Read profile ./scripts/gnu-profile
case007-gnu.c:4:3: Warning: Line split #2 at NAMES
case007-gnu.c:11:30: Warning: Line split #2 at {
case007-gnu.c:48:55: Warning: Line split #2 at {
case007-gnu.c:49:50: Warning: Line split #2 at {
case007-gnu.c:55:25: Warning: Line split #2 at {
case007-gnu.c:58:36: Warning: Line split #2 at {
There were 40 output lines and 1 comments
(Lines with comments)/(Lines with code):  0.026
** updated case007-gnu.c
