Read profile ./scripts/cdk-profile
case007-cdk.c:4:3: Warning: Line split #2 at NAMES
case007-cdk.c:11:30: Warning: Line split #2 at {
case007-cdk.c:50:55: Warning: Line split #2 at {
case007-cdk.c:51:50: Warning: Line split #2 at {
case007-cdk.c:57:25: Warning: Line split #2 at {
case007-cdk.c:60:36: Warning: Line split #2 at {
There were 39 output lines and 1 comments
(Lines with comments)/(Lines with code):  0.026
** updated case007-cdk.c
