Read profile ./scripts/yak-profile
case002-yak.c:10:67: Warning: Line split #2 at {
case002-yak.c:12:7: Warning: Line split #2 at else
case002-yak.c:12:59: Warning: Line split #2 at {
case002-yak.c:14:7: Warning: Line split #2 at else
case002-yak.c:14:81: Warning: Line split #2 at {
case002-yak.c:16:7: Warning: Line split #2 at else
case002-yak.c:16:12: Warning: Line split #2 at {
case002-yak.c:30:41: Warning: Line split #2 at {
case002-yak.c:32:7: Warning: Line split #2 at else
case002-yak.c:32:48: Warning: Line split #2 at {
case002-yak.c:44:23: Warning: Line split #2 at {
case002-yak.c:46:41: Warning: Line split #2 at {
case002-yak.c:48:11: Warning: Line split #2 at else
case002-yak.c:48:43: Warning: Line split #2 at {
case002-yak.c:50:11: Warning: Line split #2 at else
case002-yak.c:50:49: Warning: Line split #2 at {
case002-yak.c:52:11: Warning: Line split #2 at else
case002-yak.c:52:16: Warning: Line split #2 at {
There were 73 output lines and 4 comments
(Lines with comments)/(Lines with code):  0.056
** updated case002-yak.c
