Read profile ./scripts/xxx-profile
case002-xxx.c:12:7: Warning: Line split #2 at else
case002-xxx.c:14:7: Warning: Line split #2 at else
case002-xxx.c:16:7: Warning: Line split #2 at else
case002-xxx.c:32:7: Warning: Line split #2 at else
case002-xxx.c:48:11: Warning: Line split #2 at else
case002-xxx.c:50:11: Warning: Line split #2 at else
case002-xxx.c:52:11: Warning: Line split #2 at else
There were 61 output lines and 4 comments
(Lines with comments)/(Lines with code):  0.067
** updated case002-xxx.c
