#!/bin/sh
# $Id: cdk-indent,v 1.9 2005/12/30 00:32:33 tom Exp $
# Indent CDK files.
# Seems to match the style except for struct-data and single-line cases (sigh).
NOOP=no
OPTS='
--ignore-profile
--brace-indent0
--braces-after-if-line
--dont-break-procedure-type
--indent-level3
--no-blank-lines-after-commas
--no-space-after-casts

-T CDKALPHALIST
-T CDKBUTTON
-T CDKBUTTONBOX
-T CDKCALENDAR
-T CDKDIALOG
-T CDKDSCALE
-T CDKENTRY
-T CDKFSCALE
-T CDKFSELECT
-T CDKFSLIDER
-T CDKGRAPH
-T CDKHISTOGRAM
-T CDKITEMLIST
-T CDKLABEL
-T CDKMARQUEE
-T CDKMATRIX
-T CDKMENTRY
-T CDKMENU
-T CDKOBJS
-T CDKRADIO
-T CDKSCALE
-T CDKSCREEN
-T CDKSCROLL
-T CDKSELECTION
-T CDKSLIDER
-T CDKSWINDOW
-T CDKTEMPLATE
-T CDKUSCALE
-T CDKUSLIDER
-T CDKVIEWER
-T EExitType
-T PROCESSFN
-T WINDOW
-T boolean
-T bool
-T chtype
'
for name in $*
do
	case $name in
	-n)	NOOP=yes
		OPTS="$OPTS -v"
		;;
	-*)
		OPTS="$OPTS $name"
		;;
	*)
		save="${name}".a$$
		mv "$name" "$save"
		cp "$save" "$name"
		chmod u+w "$name"
		${INDENT_PROG-indent} $OPTS "$name"
		if test $NOOP = yes ; then
			if ! ( cmp -s "$name" $save )
			then
				diff -u $save "$name"
			fi
			mv "$save" "$name"
			rm -f "${name}~"
		else
			if ( cmp -s "$name" "$save" )
			then
				echo "** unchanged $name"
				rm -f "${name}" "${name}~"
				mv "$save" "$name"
			else
				echo "** updated $name"
				rm -f "$save"
			fi
		fi
		;;
	esac
done
