#!/bin/bash
#export INDENT_PROG=/usr/local/indent/bin/indent-2.0
#export INDENT_PROG=/usr/local/indent/bin/indent-2.1.0
#export INDENT_PROG=/usr/local/indent/bin/indent-2.1.1
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.0
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.1
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.2
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.3
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.4
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.5
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.6
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.7
#export INDENT_PROG=/usr/local/indent/bin/indent-2.2.8
export INDENT_PROG=/usr/bin/indent
tst-indent $*
