#!/bin/sh
# $Id: yak-indent,v 1.5 2008/11/24 21:30:12 tom Exp $
# Indent byacc files.
# Seems to match the style except for struct-data and single-line cases (sigh).
NOOP=no
OPTS='
-cd 25
--ignore-profile
--brace-indent0
--braces-after-if-line
--indent-level4
--no-blank-lines-after-commas
--no-space-after-casts
--no-space-after-function-call-names
--swallow-optional-blank-lines

-T action
-T bucket 
-T core 
-T shifts 
-T shorts
-T reductions 

'
for name in $*
do
	case $name in
	-v|-n)
		NOOP=yes
		OPTS="$OPTS -v"
		;;
	-*)
		OPTS="$OPTS $name"
		;;
	*.[ch]|*.cc|*.cpp)
		save="${name}".a$$
		test="${name}".b$$
		rm -f "$save" "$test"
		mv "$name" "$save"
		sed \
			-e '/EMPTY_MODULE(/s/)$/);/' \
			-e '/MODULE_ID(/s/)$/);/' \
			-e 's,\<GCC_NORETURN;,;//GCC_NORETURN;,' \
			-e 's,\<GCC_PRINTFLIKE(,;//GCC_PRINTFLIKE(,' \
			-e 's,\<GCC_SCANFLIKE(,;//GCC_SCANFLIKE(,' \
			-e 's,\(\<NCURSES_EXPORT_VAR\>\),//\1,' \
			"$save" >"$test"
		cp "$test" "$name"
		chmod u+w "$name"
		# ${INDENT_PROG-indent} --version
		${INDENT_PROG-indent} -npro $OPTS "$name"
		sed \
			-e '/EMPTY_MODULE(/s/);$/)/' \
			-e '/MODULE_ID(/s/);$/)/' \
			-e 's,;[ 	]*//GCC_NORETURN;, GCC_NORETURN;,' \
			-e 's,;[ 	]*//GCC_PRINTFLIKE(, GCC_PRINTFLIKE(,' \
			-e 's,;[ 	]*//GCC_SCANFLIKE(, GCC_SCANFLIKE(,' \
			-e 's,//\(\<NCURSES_EXPORT_VAR\>\),\1,' \
			"$name" >"$test"
		mv "$test" "$name"
		rm -f "${name}~"
		if test $NOOP = yes ; then
			if (cmp -s "$name" "$save" ) then
				echo "** no change: $name"
			else
				diff -u "$save" "$name"
			fi
			rm -f "$name"
			mv "$save" "$name"
		elif ( cmp -s "$name" "$save" ) ; then
			echo "** unchanged $name"
			rm -f "${name}"
			mv "$save" "$name"
		else
			echo "** updated $name"
			rm -f "$save"
		fi
		;;
	*)
		echo "** ignored:   $name"
		;;
	esac
done
