#!/bin/sh
# Indent LYNX files.
NOOP=no
OPTS='
-nbacc
--blank-lines-after-declarations
--blank-lines-after-procedures
--braces-on-if-line
--continue-at-parentheses
--cuddle-else
--dont-break-procedure-type
--indent-level4
--leave-preprocessor-space
--line-length80
--no-space-after-function-call-names
--parameter-indentation4
--space-after-cast
--space-special-semicolon
--swallow-optional-blank-lines
-T AddressDefList 
-T BOOL
-T BOOLEAN
-T CSOfield_info 
-T DIR
-T DocAddress 
-T DocObj
-T EntryInfo 
-T FILE
-T GCC_NORETURN 
-T GCC_UNUSED 
-T GroupDef 
-T GroupDefList 
-T HTAAFailReasonType 
-T HTAAProt 
-T HTAAServer 
-T HTAARealm 
-T HTAssoc 
-T HTAssocList 
-T HTAtom 
-T HTBTElement 
-T HTBTree 
-T HTChildAnchor 
-T HTChunk 
-T HTConverter 
-T HTFormat 
-T HTLinkType 
-T HTList 
-T HTParentAnchor 
-T HTParentAnchor0 
-T HTPresentation 
-T HTStream
-T HTStyle 
-T HTStyleChange 
-T HyperDoc 
-T InitResponseAPDU 
-T Item 
-T ItemList 
-T LYNX_ADDRINFO
-T LYNX_HOSTENT
-T LYUCcharset 
-T LexItem 
-T ProgramPaths 
-T SearchAPDU 
-T SearchResponseAPDU 
-T UCode_t 
-T UserDefList 
-T WAISDocumentCodes 
-T WAISDocumentHeader 
-T WAISDocumentHeadlines 
-T WAISDocumentLongHeader 
-T WAISDocumentShortHeader 
-T WAISDocumentText 
-T WAISInitResponse 
-T _cdecl
-T any 
-T bit_map 
-T bstring 
-T data_tag
-T eServerType 
-T pdu_type
-T query_term 
'
for name in $*
do
	case $name in
	-n)	NOOP=yes
		OPTS="$OPTS -v"
		;;
	-*)
		OPTS="$OPTS $name"
		;;
	*)
		save="${name}".a$$
		mv "$name" "$save"
		cp "$save" "$name"
		chmod u+w "$name"
		${INDENT_PROG-indent} -npro $OPTS "$name"
		if test $NOOP = yes ; then
			if ! ( cmp -s "$name" $save )
			then
				diff -u $save "$name"
			fi
			mv "$save" "$name"
			rm -f "${name}~"
		else
			if ( cmp -s "$name" "$save" )
			then
				echo "** unchanged $name"
				rm -f "${name}" "${name}~"
				mv "$save" "$name"
			else
				echo "** updated $name"
				rm -f "$save"
			fi
		fi
		;;
	esac
done
