#!/bin/sh
# $Id: ncu-indent,v 1.3 2002/04/28 16:00:21 tom Exp $
OPTS=
for name in $*
do
	case $name in
	-*)
		OPTS="$OPTS $name"
		;;
	*)
		save="${name}".a$$
		test="${name}".b$$
		rm -f "$save" "$test"
		mv "$name" "$save"
		sed -e '/MODULE_ID(/s/)$/);/' "$save" >"$test"
		cp "$test" "$name"
		chmod u+w "$name"
		${INDENT_PROG-indent} --version
		${INDENT_PROG-indent} $OPTS "$name"
		if ( cmp -s "$name" "$test" )
		then
			echo "** unchanged $name"
			rm -f "${name}" "${name}~"
			mv "$save" "$name"
		else
			echo "** updated $name"
			sed -e '/MODULE_ID(/s/);$/)/' "$name" >"$test"
			mv "$test" "$name"
			rm -f "$save"
		fi
		rm -f "$test"
		;;
	esac
done
