#!/bin/sh
# $Id: twm-indent,v 1.2 2019/11/23 10:01:42 tom Exp $
#****************************************************************************
#* Copyright 2019, Thomas E. Dickey                                         *
#*                                                                          *
#* Permission is hereby granted, free of charge, to any person obtaining a  *
#* copy of this software and associated documentation files (the            *
#* "Software"), to deal in the Software without restriction, including      *
#* without limitation the rights to use, copy, modify, merge, publish,      *
#* distribute, distribute with modifications, sublicense, and/or sell       *
#* copies of the Software, and to permit persons to whom the Software is    *
#* furnished to do so, subject to the following conditions:                 *
#*                                                                          *
#* The above copyright notice and this permission notice shall be included  *
#* in all copies or substantial portions of the Software.                   *
#*                                                                          *
#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS  *
#* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF               *
#* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   *
#* IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,   *
#* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR    *
#* OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR    *
#* THE USE OR OTHER DEALINGS IN THE SOFTWARE.                               *
#*                                                                          *
#* Except as contained in this notice, the name(s) of the above copyright   *
#* holders shall not be used in advertising or otherwise to promote the     *
#* sale, use or other dealings in this Software without prior written       *
#* authorization.                                                           *
#****************************************************************************/
# https://www.x.org/wiki/CodingStyle/
# https://gitlab.freedesktop.org/xorg/app/twm
#
# Reuse profile of xxx-indent, adding typedefs from twm's header files.
# This uses xorg-indent rather than xxx-indent, since there are differences.

config=xxx-profile
source=/usr/share/tdindent/$config
if [ -f $source ]
then
	mytemp=$(mktemp -d)
	trap "rm -rf $mytemp" EXIT INT QUIT TERM HUP
	target=$mytemp/$config
	cat $source >$target
	cat >>$target <<-EOF
	-T ColorPair
	-T ColormapWindow
	-T Colormaps
	-T FuncKey
	-T IconEntry
	-T IconMgr
	-T IconRegion
	-T MenuItem
	-T MenuRoot
	-T MouseButton
	-T MyFont
	-T SigProc
	-T SqueezeInfo
	-T TBWindow
	-T TWMWinConfigEntry
	-T TitleButton
	-T TwmColormap
	-T TwmWindow
	-T WList
	-T event_proc
	EOF
	INDENT_DATA=$mytemp
	export INDENT_DATA
fi

xorg-indent "$@"
