#!/bin/sh
# $Id: vtt-indent,v 1.2 2004/07/25 15:13:47 tom Exp $
# indent vttest
NOOP=no
OPTS='
-c 17
--blank-lines-after-procedures
--braces-on-if-line
--continuation-indentation0
--continue-at-parentheses
--cuddle-else
--indent-level2
--leave-preprocessor-space
--no-blank-lines-after-commas
--no-blank-lines-after-declarations
--no-space-after-function-call-names
--procnames-start-lines
--space-special-semicolon
--swallow-optional-blank-lines
--tab-size2

-T FILE
-T GCC_NORETURN
-T size_t
'
for name in $*
do
	case $name in
	-v|-n)
		NOOP=yes
		OPTS="$OPTS -v"
		;;
	-*)
		OPTS="$OPTS $name"
		;;
	*.[ch])
		save="${name}".a$$
		test="${name}".b$$
		rm -f "$save" "$test"
		mv "$name" "$save"
		sed \
			-e 's,\<GCC_NORETURN;,;//GCC_NORETURN;,' \
			"$save" >"$test"
		cp "$test" "$name"
		chmod u+w "$name"
		# ${INDENT_PROG-indent} --version
		${INDENT_PROG-indent} -npro $OPTS "$name"
		sed \
			-e 's,;[ 	]*//GCC_NORETURN;, GCC_NORETURN;,' \
			"$name" | expand -t 2 >"$test"
		mv "$test" "$name"
		rm -f "${name}~"
		if test $NOOP = yes ; then
			if (cmp -s "$name" "$save" ) then
				echo "** no change: $name"
			else
				diff -u "$save" "$name"
			fi
			rm -f "$name"
			mv "$save" "$name"
		elif ( cmp -s "$name" "$save" ) ; then
			echo "** unchanged $name"
			rm -f "${name}"
			mv "$save" "$name"
		else
			echo "** updated $name"
			rm -f "$save"
		fi
		;;
	*)
		echo "** ignored:   $name"
		;;
	esac
done
