#!/bin/sh
# $Id: xorg-indent,v 1.7 2022/10/02 17:55:04 tom Exp $
#****************************************************************************
#* Copyright 2019,2022 Thomas E. Dickey                                     *
#*                                                                          *
#* Permission is hereby granted, free of charge, to any person obtaining a  *
#* copy of this software and associated documentation files (the            *
#* "Software"), to deal in the Software without restriction, including      *
#* without limitation the rights to use, copy, modify, merge, publish,      *
#* distribute, distribute with modifications, sublicense, and/or sell       *
#* copies of the Software, and to permit persons to whom the Software is    *
#* furnished to do so, subject to the following conditions:                 *
#*                                                                          *
#* The above copyright notice and this permission notice shall be included  *
#* in all copies or substantial portions of the Software.                   *
#*                                                                          *
#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS  *
#* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF               *
#* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.   *
#* IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,   *
#* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR    *
#* OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR    *
#* THE USE OR OTHER DEALINGS IN THE SOFTWARE.                               *
#*                                                                          *
#* Except as contained in this notice, the name(s) of the above copyright   *
#* holders shall not be used in advertising or otherwise to promote the     *
#* sale, use or other dealings in this Software without prior written       *
#* authorization.                                                           *
#****************************************************************************/
# https://www.x.org/wiki/CodingStyle/, i.e., the "x-indent.sh" script.
#
# Used with these xterm dependencies:
# https://gitlab.freedesktop.org/xorg/lib/libxaw
# https://gitlab.freedesktop.org/xorg/lib/libxt
# https://gitlab.freedesktop.org/xorg/lib/libx11
#
# This uses the profile from xxx-indent, which supplies indent options and
# typedefs for consistent formatting.  This particular script assumes it uses
# gnu-indent rather than cindent, because there are some differences.

program=indent
renamed=indent-base
if $renamed --version >/dev/null 2>&1 ; then
	program=$renamed
elif [ $? = 1 ] ; then
	program=$renamed
fi
INDENT_PROG=$program xxx-indent "$@"
