#!/bin/sh
# $Id: yak-indent,v 1.3 2005/05/03 23:13:34 tom Exp $
# Indent byacc files.
# Seems to match the style except for struct-data and single-line cases (sigh).
NOOP=no
OPTS='
-cd 25
--ignore-profile
--brace-indent0
--braces-after-if-line
--dont-break-procedure-type
--indent-level4
--no-blank-lines-after-commas
--no-space-after-casts
--no-space-after-function-call-names
--swallow-optional-blank-lines

-T action
-T bucket 
-T core 
-T shifts 
-T shorts
-T reductions 

'
for name in $*
do
	case $name in
	-n)	NOOP=yes
		OPTS="$OPTS -v"
		;;
	-*)
		OPTS="$OPTS $name"
		;;
	*)
		save="${name}".a$$
		mv "$name" "$save"
		cp "$save" "$name"
		chmod u+w "$name"
		${INDENT_PROG-indent} $OPTS "$name"
		if test $NOOP = yes ; then
			if ! ( cmp -s "$name" $save )
			then
				diff -u $save "$name"
			fi
			mv "$save" "$name"
			rm -f "${name}~"
		else
			if ( cmp -s "$name" "$save" )
			then
				echo "** unchanged $name"
				rm -f "${name}" "${name}~"
				mv "$save" "$name"
			else
				echo "** updated $name"
				rm -f "$save"
			fi
		fi
		;;
	esac
done
